version: '3.8'

services:
  nasa-tempo-aqi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nasa-tempo-network

networks:
  nasa-tempo-network:
    driver: bridge

volumes:
  nasa-tempo-data:
    driver: local